### ISSUE TITLE
linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by Arcovv** [Panl/Gank.lu#2]
ld: framework not found Pods
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I try to fix this with google but failure. 

Your Development target is 9.3, but I just 9.2.

Thanks for your help.

**Comment by Panl** [comment]
you should change the target to 9.2，and input  'pod install' in command line

**Comment by Arcovv** [comment]
I change the target to 9.2, and pod install.
Also clean, but not work.

**Comment by Panl** [comment]
I don't know the detail,I use Xcode 7.3 beta3, OS X 10.11.3,try to check your Configurations, and set both debug and release to none.then pod install.

**Comment by Panl** [comment]
I have found the solution for this problem:

> In Project Navigator in the folder Pods I had a Pods.framework in there which was red. It was also present in Linked Frameworks and Libraries. I removed both references and the error disappeared.

**Remove Pods.framework in:**
- Folder named Pods
- Linked Frameworks and Libraries

from [please learn to use google](http://stackoverflow.com/questions/29865899/ld-framework-not-found-pods)
