### ISSUE TITLE
PagingMenuOptions 编译错误

### ISSUE THREAD

**Issue by Gracker** [Panl/Gank.lu#4]
Hi 我fork的库，发现PagingMenuController 这个库的使用方法变了，下面的一句编译不过：
let options = PagingMenuOptions()

**Comment by Panl** [comment]
You should read the CHANGELOG or Example in [PagingMenuController](https://github.com/kitasuke/PagingMenuController), the library updated frequently recent days.

**Comment by Mervin1024** [comment]
You are zhazha!

**Comment by Panl** [comment]
@Mervin1024 你很屌，很嚣张啊
